#!/bin/bash


function makecert() {
	ca=$1
	dir=$2
	name=$3

	echo ""
	echo "Generating certificate for: ${name}"
	echo "Using CA: \"${ca}\""
	echo "Dir: ${dir}"

	mkdir -p ${dir}
	openssl genrsa -out ${dir}/${name}-key.pem 2048
	openssl req -new -key ${dir}/${name}-key.pem -out ${dir}/${name}-csr.pem -subj "/CN=${name}"
	sudo openssl ca -batch -name ${ca} -in ${dir}/${name}-csr.pem -out ${dir}/${name}.pem

}

makecert "CA_test" "./server/" "test-server"
makecert "CA_test" "./client/" "test-client"

echo "done."

