#!/bin/bash


function makeca() {
    dir=$1
    cn=$2
    echo "Creating CA at directory \"${dir}\""
    echo "Common name(CN): ${cn}"

    test -e $dir && echo "ERROR: Directory \"$dir\" already exists" && return 1
    mkdir -pv ${dir}/newcerts
    mkdir -pv ${dir}/private
    touch ${dir}/index.txt ${dir}/serial
    echo "01" > ${dir}/serial

    openssl genrsa -out ${dir}/private/cakey.pem 2048
    openssl req -new -x509 -key ${dir}/private/cakey.pem -out ${dir}/cacert.pem -subj "/CN=${cn}"
}

[ $# -eq 2 ] && makeca $1 $2

